export const productsBackUp = [
    {
        id: "682bbf4862c226a0eb017bda",
        productName: "Carne x100",
        productDescription:
            "Carne de res, en presentación x100, ideal para alimentación de mascotas.",
        productDetails:
            "Producto de carne premium, corte fresco y de alta calidad, ideal para perros de tamaño mediano a grande.",
        imageUrl:
            "https://res.cloudinary.com/dfjpi2ypk/image/upload/v1747565952/MINI_CARNE_if05sw.png",
        sellingPrice: 5.94,
        discountPercent: 10,
        reviewsIds: ["review001", "review002", "review003"],
        categories: ["Carnes", "Alimentos para mascotas", "Perros"],
        costPrice: 4.5,
        productCode: "CARNE100",
        recipeId: "recipe001",
        stock: 500,
        createdAt: "2025-05-09T12:00:00Z",
        updatedAt: "2025-05-14T12:00:00Z",
        modifiedBy: "adminUser",
        createdBy: "adminUser",
    },
    {
        id: "682bbf4862c226a0eb017bdb",
        productName: "Carne x200",
        productDescription:
            "Carne de res, en presentación x200, ideal para alimentación de mascotas.",
        productDetails:
            "Carne fresca, de corte premium, para alimentación diaria de perros, ideal para todos los tamaños.",
        imageUrl:
            "https://res.cloudinary.com/dfjpi2ypk/image/upload/v1747565952/MINI_CARNE_if05sw.png",
        sellingPrice: 8.756,
        discountPercent: 10,
        reviewsIds: ["review004", "review005", "review006"],
        categories: ["Carnes", "Alimentos para mascotas", "Perros"],
        costPrice: 6.7,
        productCode: "CARNE200",
        recipeId: "recipe002",
        stock: 300,
        createdAt: "2025-05-09T13:00:00Z",
        updatedAt: "2025-05-14T13:00:00Z",
        modifiedBy: "adminUser",
        createdBy: "adminUser",
    },
    {
        id: "682bbf4862c226a0eb017bdc",
        productName: "Corazon x100",
        productDescription:
            "Corazón de res, en presentación x100, ideal para mascotas.",
        productDetails:
            "Corazón fresco, corte premium, especialmente preparado para perros.",
        imageUrl:
            "https://res.cloudinary.com/dfjpi2ypk/image/upload/v1747565952/MINI_CORAZON_ofnu2i.png",
        sellingPrice: 4.821,
        discountPercent: 10,
        reviewsIds: ["review007", "review008", "review009"],
        categories: ["Carnes", "Alimentos para mascotas", "Perros"],
        costPrice: 3.6,
        productCode: "CORAZON100",
        recipeId: "recipe003",
        stock: 450,
        createdAt: "2025-05-09T14:00:00Z",
        updatedAt: "2025-05-14T14:00:00Z",
        modifiedBy: "adminUser",
        createdBy: "adminUser",
    },
    {
        id: "682bbf4862c226a0eb017bdd",
        productName: "Corazon x200",
        productDescription:
            "Corazón de res, en presentación x200, ideal para mascotas.",
        productDetails:
            "Corazón de res, de alta calidad, ideal para perros de tamaño grande.",
        imageUrl:
            "https://res.cloudinary.com/dfjpi2ypk/image/upload/v1747565952/MINI_CORAZON_ofnu2i.png",
        sellingPrice: 6.16,
        discountPercent: 10,
        reviewsIds: ["review010", "review011", "review012"],
        categories: ["Carnes", "Alimentos para mascotas", "Perros"],
        costPrice: 4.2,
        productCode: "CORAZON200",
        recipeId: "recipe004",
        stock: 400,
        createdAt: "2025-05-09T15:00:00Z",
        updatedAt: "2025-05-14T15:00:00Z",
        modifiedBy: "adminUser",
        createdBy: "adminUser",
    },
    {
        id: "682bbf4862c226a0eb017bde",
        productName: "Tendones x5",
        productDescription:
            "Tendones de res, en presentación x5, ideales para perros de tamaño mediano.",
        productDetails:
            "Tendones frescos, corte grueso, preparados para la masticación diaria de perros.",
        imageUrl:
            "https://res.cloudinary.com/dfjpi2ypk/image/upload/v1747565951/TENDON_jkqs5k.png",
        sellingPrice: 6.327,
        discountPercent: 10,
        reviewsIds: ["review013", "review014", "review015"],
        categories: ["Carnes", "Alimentos para mascotas", "Perros"],
        costPrice: 4.9,
        productCode: "TENDONES5",
        recipeId: "recipe005",
        stock: 150,
        createdAt: "2025-05-09T16:00:00Z",
        updatedAt: "2025-05-14T16:00:00Z",
        modifiedBy: "adminUser",
        createdBy: "adminUser",
    },
    {
        id: "682bbf4862c226a0eb017bdf",
        productName: "Mini tendones x200",
        productDescription:
            "Mini tendones de res, en presentación x200, ideales para perros pequeños.",
        productDetails:
            "Tendones en tamaño pequeño, perfectos para perros de razas pequeñas o para entrenamiento.",
        imageUrl:
            "https://res.cloudinary.com/dfjpi2ypk/image/upload/v1747565951/TENDON_jkqs5k.png",
        sellingPrice: 5.39,
        discountPercent: 10,
        reviewsIds: ["review016", "review017", "review018"],
        categories: ["Carnes", "Alimentos para mascotas", "Perros"],
        costPrice: 3.8,
        productCode: "MINITENDONES200",
        recipeId: "recipe006",
        stock: 200,
        createdAt: "2025-05-09T17:00:00Z",
        updatedAt: "2025-05-14T17:00:00Z",
        modifiedBy: "adminUser",
        createdBy: "adminUser",
    },
    {
        id: "682bbf4862c226a0eb017be0",
        productName: "Higado x200",
        productDescription:
            "Hígados de res, en presentación x200, ideales para mascotas.",
        productDetails:
            "Hígados frescos y de alta calidad, perfectos para perros de todas las edades.",
        imageUrl:
            "https://res.cloudinary.com/dfjpi2ypk/image/upload/v1747565952/MINI_HIGADOS_djtejl.png",
        sellingPrice: 4.95,
        discountPercent: 10,
        reviewsIds: ["review019", "review020", "review021"],
        categories: ["Carnes", "Alimentos para mascotas", "Perros"],
        costPrice: 3.5,
        productCode: "HIGADO200",
        recipeId: "recipe007",
        stock: 250,
        createdAt: "2025-05-09T18:00:00Z",
        updatedAt: "2025-05-14T18:00:00Z",
        modifiedBy: "adminUser",
        createdBy: "adminUser",
    },
    {
        id: "682bbf4862c226a0eb017be1",
        productName: "Pulmon x100",
        productDescription:
            "Pulmón de res, en presentación x100, ideal para perros.",
        productDetails:
            "Pulmón fresco de alta calidad, rico en nutrientes y proteína.",
        imageUrl:
            "https://res.cloudinary.com/dfjpi2ypk/image/upload/v1747565953/MINI_PULMN_fycssi.png",
        sellingPrice: 3.22,
        discountPercent: 10,
        reviewsIds: ["review022", "review023", "review024"],
        categories: ["Carnes", "Alimentos para mascotas", "Perros"],
        costPrice: 2.5,
        productCode: "PULMON100",
        recipeId: "recipe008",
        stock: 600,
        createdAt: "2025-05-09T19:00:00Z",
        updatedAt: "2025-05-14T19:00:00Z",
        modifiedBy: "adminUser",
        createdBy: "adminUser",
    },
    {
        id: "682bbf4862c226a0eb017be2",
        productName: "Orejas x10",
        productDescription:
            "Orejas de cerdo, en presentación x10, ideales para perros.",
        productDetails:
            "Orejas de cerdo frescas, masticables y nutritivas para perros.",
        imageUrl:
            "https://res.cloudinary.com/dfjpi2ypk/image/upload/v1747565953/OREJAS_poxjk3.png",
        sellingPrice: 7.26,
        discountPercent: 10,
        reviewsIds: ["review025", "review026", "review027"],
        categories: ["Carnes", "Alimentos para mascotas", "Perros"],
        costPrice: 5.5,
        productCode: "OREJAS10",
        recipeId: "recipe009",
        stock: 350,
        createdAt: "2025-05-09T20:00:00Z",
        updatedAt: "2025-05-14T20:00:00Z",
        modifiedBy: "adminUser",
        createdBy: "adminUser",
    },
    {
        id: "682bbf4862c226a0eb017be3",
        productName: "Orejas x30",
        productDescription:
            "Orejas de cerdo, en presentación x30, ideales para perros.",
        productDetails:
            "Orejas de cerdo en presentación más grande, perfectas para perros que disfrutan masticar por más tiempo.",
        imageUrl:
            "https://res.cloudinary.com/dfjpi2ypk/image/upload/v1747565953/OREJAS_poxjk3.png",
        sellingPrice: 19.8,
        discountPercent: 10,
        reviewsIds: ["review028", "review029", "review030"],
        categories: ["Carnes", "Alimentos para mascotas", "Perros"],
        costPrice: 15,
        productCode: "OREJAS30",
        recipeId: "recipe010",
        stock: 180,
        createdAt: "2025-05-09T21:00:00Z",
        updatedAt: "2025-05-14T21:00:00Z",
        modifiedBy: "adminUser",
        createdBy: "adminUser",
    },
    {
        id: "682bbf4862c226a0eb017be4",
        productName: "Orejas x50",
        productDescription:
            "Orejas de cerdo, en presentación x50, ideales para perros.",
        productDetails:
            "Orejas de cerdo en gran cantidad, perfectas para mantener a tu perro ocupado y feliz.",
        imageUrl:
            "https://res.cloudinary.com/dfjpi2ypk/image/upload/v1747565953/OREJAS_poxjk3.png",
        sellingPrice: 29.15,
        discountPercent: 10,
        reviewsIds: ["review031", "review032", "review033"],
        categories: ["Carnes", "Alimentos para mascotas", "Perros"],
        costPrice: 23,
        productCode: "OREJAS50",
        recipeId: "recipe011",
        stock: 120,
        createdAt: "2025-05-09T22:00:00Z",
        updatedAt: "2025-05-14T22:00:00Z",
        modifiedBy: "adminUser",
        createdBy: "adminUser",
    },
    {
        id: "682bbf4862c226a0eb017be5",
        productName: "Garritas x10",
        productDescription:
            "Garritas de cerdo, en presentación x10, ideales para perros.",
        productDetails:
            "Garritas de cerdo, perfectas para perros de tamaño pequeño o mediano.",
        imageUrl:
            "https://res.cloudinary.com/dfjpi2ypk/image/upload/v1747565951/GARRITAS_DE_POLLO_vv6qx2.png",
        sellingPrice: 5.39,
        discountPercent: 10,
        reviewsIds: ["review034", "review035", "review036"],
        categories: ["Carnes", "Alimentos para mascotas", "Perros"],
        costPrice: 4,
        productCode: "GARRITAS10",
        recipeId: "recipe012",
        stock: 400,
        createdAt: "2025-05-09T23:00:00Z",
        updatedAt: "2025-05-14T23:00:00Z",
        modifiedBy: "adminUser",
        createdBy: "adminUser",
    },
    {
        id: "682bbf4862c226a0eb017be6",
        productName: "Hocicos x10",
        productDescription:
            "Hocicos de cerdo, en presentación x10, ideales para perros.",
        productDetails:
            "Hocicos de cerdo, nutritivos y deliciosos para perros de todos los tamaños.",
        imageUrl:
            "https://res.cloudinary.com/dfjpi2ypk/image/upload/v1747565952/HOCICOS_tbixb1.png",
        sellingPrice: 4.13,
        discountPercent: 10,
        reviewsIds: ["review037", "review038", "review039"],
        categories: ["Carnes", "Alimentos para mascotas", "Perros"],
        costPrice: 3.2,
        productCode: "HOCICOS10",
        recipeId: "recipe013",
        stock: 500,
        createdAt: "2025-05-10T00:00:00Z",
        updatedAt: "2025-05-15T00:00:00Z",
        modifiedBy: "adminUser",
        createdBy: "adminUser",
    },
    {
        id: "682bbf4862c226a0eb017be7",
        productName: "Mini traquea",
        productDescription: "Mini traquea de cerdo, en presentación pequeña.",
        productDetails:
            "Traqueas de cerdo pequeñas, perfectas para perros pequeños o como premio.",
        imageUrl:
            "https://res.cloudinary.com/dfjpi2ypk/image/upload/v1747565951/TRAQUEA_XL_SEGUNDA_FOTO_bgxcjr.png",
        sellingPrice: 5.632,
        discountPercent: 10,
        reviewsIds: ["review040", "review041", "review042"],
        categories: ["Carnes", "Alimentos para mascotas", "Perros"],
        costPrice: 4.2,
        productCode: "MINITRAQUEA",
        recipeId: "recipe014",
        stock: 350,
        createdAt: "2025-05-10T01:00:00Z",
        updatedAt: "2025-05-15T01:00:00Z",
        modifiedBy: "adminUser",
        createdBy: "adminUser",
    },
    {
        id: "682bbf4862c226a0eb017be8",
        productName: "Traquea",
        productDescription: "Traquea de cerdo, en presentación estándar.",
        productDetails:
            "Traqueas de cerdo, ideal para perros que disfrutan masticar por mucho tiempo.",
        imageUrl:
            "https://res.cloudinary.com/dfjpi2ypk/image/upload/v1747565951/TRAQUEA_XL_SEGUNDA_FOTO_bgxcjr.png",
        sellingPrice: 2.706,
        discountPercent: 10,
        reviewsIds: ["review043", "review044", "review045"],
        categories: ["Carnes", "Alimentos para mascotas", "Perros"],
        costPrice: 2,
        productCode: "TRAQUEA",
        recipeId: "recipe015",
        stock: 600,
        createdAt: "2025-05-10T02:00:00Z",
        updatedAt: "2025-05-15T02:00:00Z",
        modifiedBy: "adminUser",
        createdBy: "adminUser",
    },
    {
        id: "682bbf4862c226a0eb017be9",
        productName: "Orejas de cerdo x2",
        productDescription: "Orejas de cerdo, en presentación x2.",
        productDetails:
            "Orejas de cerdo pequeñas, ideales como premio para perros.",
        imageUrl:
            "https://res.cloudinary.com/dfjpi2ypk/image/upload/v1747565953/OREJAS_poxjk3.png",
        sellingPrice: 2.2,
        discountPercent: 10,
        reviewsIds: ["review046", "review047", "review048"],
        categories: ["Carnes", "Alimentos para mascotas", "Perros"],
        costPrice: 1.7,
        productCode: "OREJASCERDO2",
        recipeId: "recipe016",
        stock: 700,
        createdAt: "2025-05-10T03:00:00Z",
        updatedAt: "2025-05-15T03:00:00Z",
        modifiedBy: "adminUser",
        createdBy: "adminUser",
    },
];
