export const productsBackUp = [
    {
        id: "c8474705-8f76-4369-96e8-868bd4fc02c3",
        productName: "Carne x100",
        productDescription: "",
        productDetails: null,
        imageUrl: null,
        sellingPrice: 5400,
        discountPercent: 10,
        reviewsIds: null,
        categories: null,
        costPrice: 5940,
        productCode: "carne-x100",
        recipeId: "",
        stock: 0,
        createdAt: "2025-05-18T20:37:58.817122",
        updatedAt: null,
        modifiedBy: null,
        createdBy: "admin",
    },
    {
        id: "f00f91da-5cab-4567-af42-f6bd40453348",
        productName: "carne x200",
        productDescription: "",
        productDetails: null,
        imageUrl: null,
        sellingPrice: 7960,
        discountPercent: 10,
        reviewsIds: null,
        categories: null,
        costPrice: 8756,
        productCode: "carne-x200",
        recipeId: "",
        stock: 0,
        createdAt: "2025-05-18T20:37:58.817122",
        updatedAt: null,
        modifiedBy: null,
        createdBy: "admin",
    },
    {
        id: "48b4db1f-566c-44bb-90bc-e306b576ba07",
        productName: "corazon x100",
        productDescription:
            "Corazón de res deshidratado de forma 100% natural, libre de químicos y conservantes.\n\nEl corazón vacuno es un músculo rico en vitaminas del grupo B. Ayuda a la prevención de la anemia, y a mantener la piel y el pelo de nuestros perris/michis brillante y sana. Al ser una carne rica en hierro, potasio, magnesio y fósforo, ayuda a equilibrar los procesos vitales del cuerpo 🐶\n\nIngrediente único: corazón de res\n\n✔️ Recomendación: Este snack es ideal para premiar a tu perri y para actividades de olfato, como esconderlos por la casa o en una una alfombra olfativa para que se diviertan mientras descargan estrés y energía.\n\nPresentación: Contenido neto 100gr o 200gr\n\nApto para perros y gatos a partir de los 3 meses de edad.",
        productDetails: null,
        imageUrl: null,
        sellingPrice: 4410,
        discountPercent: 10,
        reviewsIds: null,
        categories: null,
        costPrice: 4821,
        productCode: "corazon-x100",
        recipeId: "",
        stock: 0,
        createdAt: "2025-05-18T20:37:58.817122",
        updatedAt: null,
        modifiedBy: null,
        createdBy: "admin",
    },
    {
        id: "17b5c64a-4112-4370-a813-9c52eefff0f6",
        productName: "corazon x200",
        productDescription:
            "Corazón de res deshidratado de forma 100% natural, libre de químicos y conservantes.\n\nEl corazón vacuno es un músculo rico en vitaminas del grupo B. Ayuda a la prevención de la anemia, y a mantener la piel y el pelo de nuestros perris/michis brillante y sana. Al ser una carne rica en hierro, potasio, magnesio y fósforo, ayuda a equilibrar los procesos vitales del cuerpo 🐶\n\nIngrediente único: corazón de res\n\n✔️ Recomendación: Este snack es ideal para premiar a tu perri y para actividades de olfato, como esconderlos por la casa o en una una alfombra olfativa para que se diviertan mientras descargan estrés y energía.\n\nPresentación: Contenido neto 100gr o 200gr\n\nApto para perros y gatos a partir de los 3 meses de edad.",
        productDetails: null,
        imageUrl: null,
        sellingPrice: 7056,
        discountPercent: 10,
        reviewsIds: null,
        categories: null,
        costPrice: 6160,
        productCode: "corazon-x200",
        recipeId: "",
        stock: 0,
        createdAt: "2025-05-18T20:37:58.817122",
        updatedAt: null,
        modifiedBy: null,
        createdBy: "admin",
    },
    {
        id: "f6fea472-1bd4-49b4-b828-71837992e0f4",
        productName: "tendones x5",
        productDescription:
            "Tendones de res deshidratados de forma 100% natural, libre de químicos y conservantes.\n\nEste snack es rico en glucosamina y colágeno que ayuda a las articulaciones, son ideales para ejercitar y saciar la masticación de tu perri. Además de ser ricos y saludables, son un entretenimiento perfecto al mismo tiempo que contribuyen a la limpieza dental🐶\n\nIngrediente único: tendón de res\n\nRecomendación: Si tu peludo sufre ansiedad cuando queda solo, podés dejarle este divertido y delicioso snack.\n\nPresentación: mini tendones x200gr\n\nApto para perros a partir de los 3 meses de edad.",
        productDetails: null,
        imageUrl: null,
        sellingPrice: 5670,
        discountPercent: 10,
        reviewsIds: null,
        categories: null,
        costPrice: 6327,
        productCode: "tendones-x5",
        recipeId: "",
        stock: 0,
        createdAt: "2025-05-18T20:37:58.817122",
        updatedAt: null,
        modifiedBy: null,
        createdBy: "admin",
    },
    {
        id: "d723797b-61b3-4398-a569-7f463f4c40ad",
        productName: "mini tendones x200",
        productDescription:
            "Tendones de res deshidratados de forma 100% natural, libre de químicos y conservantes.\n\nEste snack es rico en glucosamina y colágeno que ayuda a las articulaciones, son ideales para ejercitar y saciar la masticación de tu perri. Además de ser ricos y saludables, son un entretenimiento perfecto al mismo tiempo que contribuyen a la limpieza dental🐶\n\nIngrediente único: tendón de res\n\nRecomendación: Si tu peludo sufre ansiedad cuando queda solo, podés dejarle este divertido y delicioso snack.\n\nPresentación: mini tendones x200gr\n\nApto para perros a partir de los 3 meses de edad.",
        productDetails: null,
        imageUrl: null,
        sellingPrice: 4900,
        discountPercent: 10,
        reviewsIds: null,
        categories: null,
        costPrice: 5390,
        productCode: "mini-tendones-x200",
        recipeId: "",
        stock: 0,
        createdAt: "2025-05-18T20:37:58.817122",
        updatedAt: null,
        modifiedBy: null,
        createdBy: "admin",
    },
    {
        id: "a77bd2a7-312b-437b-857e-0cf35e0de76e",
        productName: "higado x200",
        productDescription:
            "Higado de res deshidratado de forma 100% natural, libre de químicos y conservantes.\n\nEl alto contenido de hierro de este snack ayuda a potenciar la energía y vitalidad de tu peludo. Además, aporta ácidos grasos esenciales, y vitaminas A y B fundamentales para la salud de tu perri/michi 🐶\n\nIngrediente único: hígado de res\n\n✔️ Recomendación: Este snack es ideal para premiar a tu perri y para actividades de olfato, como esconderlos por la casa o en una una alfombra olfativa para que se diviertan mientras descargan estrés y energía.\n\nPresentación: Contenido neto 200gr\n\nApto para perros y gatos a partir de los 3 meses de edad.",
        productDetails: null,
        imageUrl: null,
        sellingPrice: 4500,
        discountPercent: 10,
        reviewsIds: null,
        categories: null,
        costPrice: 4950,
        productCode: "higado-x200",
        recipeId: "",
        stock: 0,
        createdAt: "2025-05-18T20:37:58.817122",
        updatedAt: null,
        modifiedBy: null,
        createdBy: "admin",
    },
    {
        id: "91dfe369-3edb-4355-b5a2-330aa0d33e8a",
        productName: "pulmon x100",
        productDescription:
            "Pulmón de res deshidratado de forma 100% natural, libre de químicos y conservantes.\n\nEl pulmón es una fuente de proteínas de alta calidad y vitaminas del grupo B, por lo que son una muy buena opción para suplementar la alimentación de tu perri/michi y equilibrar los procesos vitales del cuerpo 🐶\n\nIngrediente único: pulmón de res\n\n✔️ Recomendación: Este snack es ideal para premiar a tu perri y para actividades de olfato, como esconderlos por la casa o en una una alfombra olfativa para que se diviertan mientras descargan estrés y energía.\n\nPresentación: Contenido neto 100gr\n\nApto para perros y gatos a partir de los 3 meses de edad.",
        productDetails: null,
        imageUrl: null,
        sellingPrice: 2700,
        discountPercent: 10,
        reviewsIds: null,
        categories: null,
        costPrice: 3220,
        productCode: "pulmon-x100",
        recipeId: "",
        stock: 0,
        createdAt: "2025-05-18T20:37:58.817122",
        updatedAt: null,
        modifiedBy: null,
        createdBy: "admin",
    },
    {
        id: "1dece671-7911-47bf-b2e7-cf97a8b06513",
        productName: "orejas x10",
        productDescription:
            "Orejas de cerdo deshidratadas de forma 100% natural, libre de químicos y conservantes.\n\nLas orejas de cerdo son ideales para ejercitar y saciar la masticación de tu perri. Además de ser ricas y saludables, son un entretenimiento perfecto al mismo tiempo que contribuyen a la limpieza dental 🐶\n\nRecomendación: Si tu peludo sufre ansiedad cuando queda solo, podés dejarle este divertido y delicioso snack.\n\nIngrediente único: oreja de cerdo\n\nPresentación: 50 orejas de cerdo a granel.\n\nApto para perros a partir de los 3 meses de edad.",
        productDetails: null,
        imageUrl: null,
        sellingPrice: 7000,
        discountPercent: 10,
        reviewsIds: null,
        categories: null,
        costPrice: 7260,
        productCode: "orejas-x10",
        recipeId: "",
        stock: 0,
        createdAt: "2025-05-18T20:37:58.817122",
        updatedAt: null,
        modifiedBy: null,
        createdBy: "admin",
    },
    {
        id: "824a6312-c90e-4299-983e-4ad5840758d3",
        productName: "orejas x30",
        productDescription:
            "Orejas de cerdo deshidratadas de forma 100% natural, libre de químicos y conservantes.\n\nLas orejas de cerdo son ideales para ejercitar y saciar la masticación de tu perri. Además de ser ricas y saludables, son un entretenimiento perfecto al mismo tiempo que contribuyen a la limpieza dental 🐶\n\nRecomendación: Si tu peludo sufre ansiedad cuando queda solo, podés dejarle este divertido y delicioso snack.\n\nIngrediente único: oreja de cerdo\n\nPresentación: 50 orejas de cerdo a granel.\n\nApto para perros a partir de los 3 meses de edad.",
        productDetails: null,
        imageUrl: null,
        sellingPrice: 18000,
        discountPercent: 10,
        reviewsIds: null,
        categories: null,
        costPrice: 19800,
        productCode: "orejas-x30",
        recipeId: "",
        stock: 0,
        createdAt: "2025-05-18T20:37:58.817122",
        updatedAt: null,
        modifiedBy: null,
        createdBy: "admin",
    },
    {
        id: "bf1724c3-3d40-4e1d-bde1-239a11f8671b",
        productName: "orejas x50",
        productDescription:
            "Orejas de cerdo deshidratadas de forma 100% natural, libre de químicos y conservantes.\n\nLas orejas de cerdo son ideales para ejercitar y saciar la masticación de tu perri. Además de ser ricas y saludables, son un entretenimiento perfecto al mismo tiempo que contribuyen a la limpieza dental 🐶\n\nRecomendación: Si tu peludo sufre ansiedad cuando queda solo, podés dejarle este divertido y delicioso snack.\n\nIngrediente único: oreja de cerdo\n\nPresentación: 50 orejas de cerdo a granel.\n\nApto para perros a partir de los 3 meses de edad.",
        productDetails: null,
        imageUrl: null,
        sellingPrice: 26500,
        discountPercent: 10,
        reviewsIds: null,
        categories: null,
        costPrice: 29150,
        productCode: "orejas-x50",
        recipeId: "",
        stock: 0,
        createdAt: "2025-05-18T20:37:58.817122",
        updatedAt: null,
        modifiedBy: null,
        createdBy: "admin",
    },
    {
        id: "317b3861-cc29-4533-ad72-13c704638c99",
        productName: "garritas x10",
        productDescription:
            "Garritas de pollo deshidratadas de forma 100% natural, libre de químicos y conservantes.\n\nLas garritas de pollo son ideales para ejercitar y saciar la masticación de tu perri. Además de ser ricas y saludables, son un entretenimiento perfecto al mismo tiempo que contribuyen a la limpieza dental 🐶\n\nRecomendación: Si tu peludo sufre ansiedad cuando queda solo, podés dejarle este divertido y delicioso snack.\n\nIngrediente único: garritas de pollo\n\nPresentación: 10 garritas por paquete\n\nApto para perros a partir de los 3 meses de edad.",
        productDetails: null,
        imageUrl: null,
        sellingPrice: 4500,
        discountPercent: 10,
        reviewsIds: null,
        categories: null,
        costPrice: 5390,
        productCode: "garritas-x10",
        recipeId: "",
        stock: 0,
        createdAt: "2025-05-18T20:37:58.817122",
        updatedAt: null,
        modifiedBy: null,
        createdBy: "admin",
    },
    {
        id: "ce9426c0-2c36-48a0-9b8e-67aea4fb5279",
        productName: "hocicos x10",
        productDescription:
            "Hocicos de cerdo deshidratadas de forma 100% natural, libre de químicos y conservantes.\n\nLos hocicos de cerdo son ideales para ejercitar y saciar la masticación de tu perri. Además de ser ricos y saludables, son un entretenimiento perfecto al mismo tiempo que contribuyen a la limpieza dental 🐶\n\nRecomendación: Si tu peludo sufre ansiedad cuando queda solo, podés dejarle este divertido y delicioso snack.\n\nIngrediente único: hocicos de cerdo\n\nPresentación: 10 hocicos por paquete\n\nApto para perros a partir de los 3 meses de edad.",
        productDetails: null,
        imageUrl: null,
        sellingPrice: 3850,
        discountPercent: 10,
        reviewsIds: null,
        categories: null,
        costPrice: 4130,
        productCode: "hocicos-x10",
        recipeId: "",
        stock: 0,
        createdAt: "2025-05-18T20:37:58.817122",
        updatedAt: null,
        modifiedBy: null,
        createdBy: "admin",
    },
    {
        id: "3fea8bed-b91f-475f-ab73-97879de4a7f4",
        productName: "mini traquea",
        productDescription:
            "Tráquea de res deshidratadas de forma 100% natural, libre de químicos y conservantes.\n\nLas tráqueas son ideales para ejercitar y saciar la masticación de tu perri. Además de ser ricas y saludables, son un entretenimiento perfecto al mismo tiempo que contribuyen a la limpieza dental 🐶\n\nRecomendación: Las podés rellenar con paté, queso o algún yogurt natural\n\nIngrediente único: Tráquea de res\n\nPresentación: 2 tráqueas cortadas en pedazos\n\nApto para perros a partir de los 3 meses de edad.",
        productDetails: null,
        imageUrl: null,
        sellingPrice: 5120,
        discountPercent: 10,
        reviewsIds: null,
        categories: null,
        costPrice: 5632,
        productCode: "mini-traquea",
        recipeId: "",
        stock: 0,
        createdAt: "2025-05-18T20:37:58.817122",
        updatedAt: null,
        modifiedBy: null,
        createdBy: "admin",
    },
    {
        id: "7326f218-fc6c-4486-a2a5-f14bd6c60c51",
        productName: "traquea",
        productDescription:
            "Tráquea de res deshidratadas de forma 100% natural, libre de químicos y conservantes.\n\nLas tráqueas son ideales para ejercitar y saciar la masticación de tu perri. Además de ser ricas y saludables, son un entretenimiento perfecto al mismo tiempo que contribuyen a la limpieza dental 🐶\n\nRecomendación: Las podés rellenar con paté, queso o algún yogurt natural\n\nIngrediente único: Tráquea de res\n\nPresentación: 2 tráqueas cortadas en pedazos\n\nApto para perros a partir de los 3 meses de edad.",
        productDetails: null,
        imageUrl: null,
        sellingPrice: 2460,
        discountPercent: 10,
        reviewsIds: null,
        categories: null,
        costPrice: 2706,
        productCode: "traquea",
        recipeId: "",
        stock: 0,
        createdAt: "2025-05-18T20:37:58.817122",
        updatedAt: null,
        modifiedBy: null,
        createdBy: "admin",
    },
    {
        id: "28787561-a44b-467e-9658-2c4f6a6268f4",
        productName: "orejas de cerdo x2",
        productDescription:
            "Orejas de cerdo deshidratadas de forma 100% natural, libre de químicos y conservantes.\n\nLas orejas de cerdo son ideales para ejercitar y saciar la masticación de tu perri. Además de ser ricas y saludables, son un entretenimiento perfecto al mismo tiempo que contribuyen a la limpieza dental 🐶\n\nRecomendación: Si tu peludo sufre ansiedad cuando queda solo, podés dejarle este divertido y delicioso snack.\n\nIngrediente único: oreja de cerdo\n\nPresentación: 50 orejas de cerdo a granel.\n\nApto para perros a partir de los 3 meses de edad.",
        productDetails: null,
        imageUrl: null,
        sellingPrice: 2000,
        discountPercent: 10,
        reviewsIds: null,
        categories: null,
        costPrice: 2200,
        productCode: "orejas-de-cerdo-x2",
        recipeId: "",
        stock: 0,
        createdAt: "2025-05-18T20:37:58.817122",
        updatedAt: null,
        modifiedBy: null,
        createdBy: "admin",
    },
];
